<PlayerScreen>:

    name: 'player'
    FloatLayout:
        id: float
        size_hint: None, None


    ImageButton:
        id: leaderboard
        source: 'assets/images/timer/time_left_64.png'
        center_x: root.width * 0.82
        center_y: root.height * 0.95
        size: 128, 64



    DPEAButton:
        id: transition
        text: "Play!"
        size: 200, 100
        x: 0
        y: 0
        color: 0.65, 0, 0.25, 1
        on_press: root.transition_to_target_screen()


