<PlayerScreen>:

    name: 'player'
    FloatLayout:
        id: float
        size_hint: None, None


    ImageButton:
        id: leaderboard
        source: 'assets/images/text/leaderboard.png'
        x: root.width / 2 - 396 / 2
        y: root.height - 44*3
        size: 396, 44



    DPEAButton:
        id: transition
        text: "Play!"
        size: 200, 100
        x: 0
        y: 0
        color: 0.65, 0, 0.25, 1
        on_press: root.transition_to_target_screen()


